spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sorion
      ?useUnicode=true
      &characterEncoding=utf8
      &useSSL=false
      &allowPublicKeyRetrieval=true
      &serverTimezone=Asia/Seoul
    username: root
    password: qkfka1396

  jpa:
    hibernate:
      ddl-auto: create     # 개발: update 권장 / 운영: validate 또는 none + Flyway
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul        # 타임존 정합성
        # dialect는 부트가 자동 설정하므로 보통 생략

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace  # 바인딩 값까지 보고 싶을 때만
